version: '3.8'


services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head &&
            gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --reload --bind=0.0.0.0:8000"
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    networks:
      - local
    depends_on:
      - postgres
      - redis
      
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - local
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - local


networks:
  local:
    driver: bridge
  
volumes:
  postgres_data:
  redis_data: