version: '3.8'


services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head &&
            uvicorn app.main:app --reload --host '0.0.0.0'"
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - local
    depends_on:
      - postgres
      - redis
      
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ryan_gosling
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=quizz_app 
    networks:
      - local

  # test_postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - test_postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=test_user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=test 
  #   networks:
  #     - local

  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - local


networks:
  local:
    driver: bridge
  
volumes:
  postgres_data:
  redis_data:
  # test_postgres_data:
