"""initial migration

Revision ID: 000728f81c69
Revises: 
Create Date: 2023-10-18 09:44:40.750747

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "000728f81c69"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
