"""add user phone number

Revision ID: 533a799aee1a
Revises: 763809db8dd7
Create Date: 2023-11-01 16:40:43.218639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "533a799aee1a"
down_revision = "763809db8dd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
