"""split up quiz deadlines into separate date and time fields

Revision ID: e8c0d95eb517
Revises: 7700e2b0d730
Create Date: 2023-11-15 17:54:25.932437

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8c0d95eb517"
down_revision = "7700e2b0d730"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quizzes", sa.Column("start_date", sa.String(), nullable=False))
    op.add_column("quizzes", sa.Column("end_date", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quizzes", "end_date")
    op.drop_column("quizzes", "start_date")
    # ### end Alembic commands ###
