"""alter tag model unique constraint

Revision ID: ea3fc145f654
Revises: 1683f50bbfc1
Create Date: 2023-11-05 22:18:21.388524

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea3fc145f654"
down_revision = "1683f50bbfc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tags_title_key", "tags", type_="unique")
    op.create_unique_constraint("_tag_uc", "tags", ["title", "company_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_tag_uc", "tags", type_="unique")
    op.create_unique_constraint("tags_title_key", "tags", ["title"])
    # ### end Alembic commands ###
